use core::*;

// Unary Tags
pub fn br() -> Fragment { tag("br", true, vec![]) }
pub fn hr(children: &[Fragment]) -> Fragment { tag("hr", true, children.to_vec()) }

// Binary tags
pub fn a(children: &[Fragment]) -> Fragment { tag("a", false, children.to_vec()) }
pub fn abbr(children: &[Fragment]) -> Fragment { tag("abbr", false, children.to_vec()) }
pub fn acronym(children: &[Fragment]) -> Fragment { tag("acronym", false, children.to_vec()) }
pub fn address(children: &[Fragment]) -> Fragment { tag("address", false, children.to_vec()) }
pub fn applet(children: &[Fragment]) -> Fragment { tag("applet", false, children.to_vec()) }
pub fn area(children: &[Fragment]) -> Fragment { tag("area", false, children.to_vec()) }
pub fn article(children: &[Fragment]) -> Fragment { tag("article", false, children.to_vec()) }
pub fn aside(children: &[Fragment]) -> Fragment { tag("aside", false, children.to_vec()) }
pub fn audio(children: &[Fragment]) -> Fragment { tag("audio", false, children.to_vec()) }
pub fn b(children: &[Fragment]) -> Fragment { tag("b", false, children.to_vec()) }
pub fn base(children: &[Fragment]) -> Fragment { tag("base", false, children.to_vec()) }
pub fn basefont(children: &[Fragment]) -> Fragment { tag("basefont", false, children.to_vec()) }
pub fn bdi(children: &[Fragment]) -> Fragment { tag("bdi", false, children.to_vec()) }
pub fn bdo(children: &[Fragment]) -> Fragment { tag("bdo", false, children.to_vec()) }
pub fn big(children: &[Fragment]) -> Fragment { tag("big", false, children.to_vec()) }
pub fn blockquote(children: &[Fragment]) -> Fragment { tag("blockquote", false, children.to_vec()) }
pub fn body(children: &[Fragment]) -> Fragment { tag("body", false, children.to_vec()) }
pub fn button(children: &[Fragment]) -> Fragment { tag("button", false, children.to_vec()) }
pub fn canvas(children: &[Fragment]) -> Fragment { tag("canvas", false, children.to_vec()) }
pub fn caption(children: &[Fragment]) -> Fragment { tag("caption", false, children.to_vec()) }
pub fn center(children: &[Fragment]) -> Fragment { tag("center", false, children.to_vec()) }
pub fn cite(children: &[Fragment]) -> Fragment { tag("cite", false, children.to_vec()) }
pub fn code(children: &[Fragment]) -> Fragment { tag("code", false, children.to_vec()) }
pub fn col(children: &[Fragment]) -> Fragment { tag("col", false, children.to_vec()) }
pub fn colgroup(children: &[Fragment]) -> Fragment { tag("colgroup", false, children.to_vec()) }
pub fn datalist(children: &[Fragment]) -> Fragment { tag("datalist", false, children.to_vec()) }
pub fn dd(children: &[Fragment]) -> Fragment { tag("dd", false, children.to_vec()) }
pub fn del(children: &[Fragment]) -> Fragment { tag("del", false, children.to_vec()) }
pub fn details(children: &[Fragment]) -> Fragment { tag("details", false, children.to_vec()) }
pub fn dfn(children: &[Fragment]) -> Fragment { tag("dfn", false, children.to_vec()) }
pub fn dialog(children: &[Fragment]) -> Fragment { tag("dialog", false, children.to_vec()) }
pub fn dir(children: &[Fragment]) -> Fragment { tag("dir", false, children.to_vec()) }
pub fn div(children: &[Fragment]) -> Fragment { tag("div", false, children.to_vec()) }
pub fn dl(children: &[Fragment]) -> Fragment { tag("dl", false, children.to_vec()) }
pub fn dt(children: &[Fragment]) -> Fragment { tag("dt", false, children.to_vec()) }
pub fn em(children: &[Fragment]) -> Fragment { tag("em", false, children.to_vec()) }
pub fn embed(children: &[Fragment]) -> Fragment { tag("embed", false, children.to_vec()) }
pub fn fieldset(children: &[Fragment]) -> Fragment { tag("fieldset", false, children.to_vec()) }
pub fn figcaption(children: &[Fragment]) -> Fragment { tag("figcaption", false, children.to_vec()) }
pub fn figure(children: &[Fragment]) -> Fragment { tag("figure", false, children.to_vec()) }
pub fn font(children: &[Fragment]) -> Fragment { tag("font", false, children.to_vec()) }
pub fn footer(children: &[Fragment]) -> Fragment { tag("footer", false, children.to_vec()) }
pub fn form(children: &[Fragment]) -> Fragment { tag("form", false, children.to_vec()) }
pub fn frame(children: &[Fragment]) -> Fragment { tag("frame", false, children.to_vec()) }
pub fn frameset(children: &[Fragment]) -> Fragment { tag("frameset", false, children.to_vec()) }
pub fn h1(children: &[Fragment]) -> Fragment { tag("h1", false, children.to_vec()) }
pub fn h2(children: &[Fragment]) -> Fragment { tag("h2", false, children.to_vec()) }
pub fn h3(children: &[Fragment]) -> Fragment { tag("h3", false, children.to_vec()) }
pub fn h4(children: &[Fragment]) -> Fragment { tag("h4", false, children.to_vec()) }
pub fn h5(children: &[Fragment]) -> Fragment { tag("h5", false, children.to_vec()) }
pub fn h6(children: &[Fragment]) -> Fragment { tag("h6", false, children.to_vec()) }
pub fn head(children: &[Fragment]) -> Fragment { tag("head", false, children.to_vec()) }
pub fn header(children: &[Fragment]) -> Fragment { tag("header", false, children.to_vec()) }
pub fn html(children: &[Fragment]) -> Fragment { tag("html", false, children.to_vec()) }
pub fn i(children: &[Fragment]) -> Fragment { tag("i", false, children.to_vec()) }
pub fn iframe(children: &[Fragment]) -> Fragment { tag("iframe", false, children.to_vec()) }
pub fn img(children: &[Fragment]) -> Fragment { tag("img", false, children.to_vec()) }
pub fn input(children: &[Fragment]) -> Fragment { tag("input", false, children.to_vec()) }
pub fn ins(children: &[Fragment]) -> Fragment { tag("ins", false, children.to_vec()) }
pub fn kbd(children: &[Fragment]) -> Fragment { tag("kbd", false, children.to_vec()) }
pub fn label(children: &[Fragment]) -> Fragment { tag("label", false, children.to_vec()) }
pub fn legend(children: &[Fragment]) -> Fragment { tag("legend", false, children.to_vec()) }
pub fn li(children: &[Fragment]) -> Fragment { tag("li", false, children.to_vec()) }
pub fn link(children: &[Fragment]) -> Fragment { tag("link", false, children.to_vec()) }
pub fn main(children: &[Fragment]) -> Fragment { tag("main", false, children.to_vec()) }
pub fn map(children: &[Fragment]) -> Fragment { tag("map", false, children.to_vec()) }
pub fn mark(children: &[Fragment]) -> Fragment { tag("mark", false, children.to_vec()) }
pub fn menu(children: &[Fragment]) -> Fragment { tag("menu", false, children.to_vec()) }
pub fn menuitem(children: &[Fragment]) -> Fragment { tag("menuitem", false, children.to_vec()) }
pub fn meta(children: &[Fragment]) -> Fragment { tag("meta", false, children.to_vec()) }
pub fn meter(children: &[Fragment]) -> Fragment { tag("meter", false, children.to_vec()) }
pub fn nav(children: &[Fragment]) -> Fragment { tag("nav", false, children.to_vec()) }
pub fn noframes(children: &[Fragment]) -> Fragment { tag("noframes", false, children.to_vec()) }
pub fn noscript(children: &[Fragment]) -> Fragment { tag("noscript", false, children.to_vec()) }
pub fn object(children: &[Fragment]) -> Fragment { tag("object", false, children.to_vec()) }
pub fn ol(children: &[Fragment]) -> Fragment { tag("ol", false, children.to_vec()) }
pub fn optgroup(children: &[Fragment]) -> Fragment { tag("optgroup", false, children.to_vec()) }
pub fn option(children: &[Fragment]) -> Fragment { tag("option", false, children.to_vec()) }
pub fn output(children: &[Fragment]) -> Fragment { tag("output", false, children.to_vec()) }
pub fn p(children: &[Fragment]) -> Fragment { tag("p", false, children.to_vec()) }
pub fn param(children: &[Fragment]) -> Fragment { tag("param", false, children.to_vec()) }
pub fn picture(children: &[Fragment]) -> Fragment { tag("picture", false, children.to_vec()) }
pub fn pre(children: &[Fragment]) -> Fragment { tag("pre", false, children.to_vec()) }
pub fn progress(children: &[Fragment]) -> Fragment { tag("progress", false, children.to_vec()) }
pub fn q(children: &[Fragment]) -> Fragment { tag("q", false, children.to_vec()) }
pub fn rp(children: &[Fragment]) -> Fragment { tag("rp", false, children.to_vec()) }
pub fn rt(children: &[Fragment]) -> Fragment { tag("rt", false, children.to_vec()) }
pub fn ruby(children: &[Fragment]) -> Fragment { tag("ruby", false, children.to_vec()) }
pub fn s(children: &[Fragment]) -> Fragment { tag("s", false, children.to_vec()) }
pub fn samp(children: &[Fragment]) -> Fragment { tag("samp", false, children.to_vec()) }
pub fn script(children: &[Fragment]) -> Fragment { tag("script", false, children.to_vec()) }
pub fn section(children: &[Fragment]) -> Fragment { tag("section", false, children.to_vec()) }
pub fn select(children: &[Fragment]) -> Fragment { tag("select", false, children.to_vec()) }
pub fn small(children: &[Fragment]) -> Fragment { tag("small", false, children.to_vec()) }
pub fn source(children: &[Fragment]) -> Fragment { tag("source", false, children.to_vec()) }
pub fn span(children: &[Fragment]) -> Fragment { tag("span", false, children.to_vec()) }
pub fn strike(children: &[Fragment]) -> Fragment { tag("strike", false, children.to_vec()) }
pub fn strong(children: &[Fragment]) -> Fragment { tag("strong", false, children.to_vec()) }
pub fn style(children: &[Fragment]) -> Fragment { tag("style", false, children.to_vec()) }
pub fn sub(children: &[Fragment]) -> Fragment { tag("sub", false, children.to_vec()) }
pub fn summary(children: &[Fragment]) -> Fragment { tag("summary", false, children.to_vec()) }
pub fn sup(children: &[Fragment]) -> Fragment { tag("sup", false, children.to_vec()) }
pub fn table(children: &[Fragment]) -> Fragment { tag("table", false, children.to_vec()) }
pub fn tbody(children: &[Fragment]) -> Fragment { tag("tbody", false, children.to_vec()) }
pub fn td(children: &[Fragment]) -> Fragment { tag("td", false, children.to_vec()) }
pub fn template(children: &[Fragment]) -> Fragment { tag("template", false, children.to_vec()) }
pub fn textarea(children: &[Fragment]) -> Fragment { tag("textarea", false, children.to_vec()) }
pub fn tfoot(children: &[Fragment]) -> Fragment { tag("tfoot", false, children.to_vec()) }
pub fn th(children: &[Fragment]) -> Fragment { tag("th", false, children.to_vec()) }
pub fn thead(children: &[Fragment]) -> Fragment { tag("thead", false, children.to_vec()) }
pub fn time(children: &[Fragment]) -> Fragment { tag("time", false, children.to_vec()) }
pub fn title(children: &[Fragment]) -> Fragment { tag("title", false, children.to_vec()) }
pub fn tr(children: &[Fragment]) -> Fragment { tag("tr", false, children.to_vec()) }
pub fn track(children: &[Fragment]) -> Fragment { tag("track", false, children.to_vec()) }
pub fn tt(children: &[Fragment]) -> Fragment { tag("tt", false, children.to_vec()) }
pub fn u(children: &[Fragment]) -> Fragment { tag("u", false, children.to_vec()) }
pub fn ul(children: &[Fragment]) -> Fragment { tag("ul", false, children.to_vec()) }
pub fn var(children: &[Fragment]) -> Fragment { tag("var", false, children.to_vec()) }
pub fn video(children: &[Fragment]) -> Fragment { tag("video", false, children.to_vec()) }
pub fn wbr(children: &[Fragment]) -> Fragment { tag("wbr", false, children.to_vec()) }
